### ISSUE TITLE
Topics for newsletter July 2021

### ISSUE THREAD

**Issue by sandragesing** [USRSE/newsletters#3]

**Comment by vsoch** [comment]
RSE Stories! https://us-rse.org/rse-stories/archive/

**Comment by sandragesing** [comment]
> RSE Stories! https://us-rse.org/rse-stories/archive/

They will continue to be part of the newsletters like interesting events.

**Comment by vsoch** [comment]
ah okay, thank you!

**Comment by JeffCarver** [comment]
Add links to US-RSE Virtual Workshop videos:

Day 1: https://youtu.be/P32RYY_2V7w
Day 2: https://youtu.be/b6Cv744k8YM

**Comment by cmaimone** [comment]
Research Study on Research Computing and Data Workforce
https://carcc.org/rcd-professionalization/rcdprof-census/research-study-on-research-computing-and-data-workforce/

The Campus Research Computing Consortium (CaRCC) Professionalization Working Group and Northwestern University invite members of the Research Computing and Data (RCD) community (including research software engineers!) to participate in a research study of the Research Computing and Data (RCD) workforce in the United States: Research Computing Workforce Survey. 

This study aims to provide the first large data set on the composition of the RCD workforce in terms of demographics, job responsibilities, job types, compensation, and perceptions of the RCD field. The study is limited to the United States due to varying data privacy laws and research requirements internationally.  The survey results will be widely shared with the community.

The survey takes approximately 20 minutes to complete.  [Take the Survey](https://northwestern.az1.qualtrics.com/jfe/form/SV_8345y1KCls4nNci)

**Comment by cosden** [comment]
A few things:
1. In the RSE stories section, it would be good to mention that Peter has left the podcast and there is room for a new host and volunteers. 
2. The new DEI statement and overall mission statement

**Comment by vsoch** [comment]
Thank you @cosden! Yes, there is always room for new hosts and volunteers! I probably won't do this forever, as we get more developed and successful the need for the podcast goes down. But I still get contacted every now and then with people saying thank you, so I'll keep it up a little longer.

**Comment by cferenba** [comment]
Will add the CFP for the SC21 workshop.

**Comment by cosden** [comment]
The international RSE survey is likely to go live around Aug 1. A short "keep an eye out" and "please take the time to complete it" in the newsletter would be good to include.

**Comment by JeffCarver** [comment]
July Community Call video: https://youtu.be/hRh82FKGr4k

**Comment by JeffCarver** [comment]
I would like to add a link to a survey that some colleagues and I have just launched. @sandragesing I can talk with you more about what is appropriate to put in the newsletter.
